name: 'jaffle_shop_iceberg'
version: '1.0.0'
config-version: 2

profile: 'jaffle_shop_iceberg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  jaffle_shop_iceberg:
    +table_type: iceberg
    +format: parquet
