services:
  postgres:
    image: postgres:17.5
    container_name: dbt_zakka_mall
    environment:
      POSTGRES_DB: dbt_demo
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - dbt_ch4_postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dbt_ch4_network

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: dbt_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dbt_user@example.com
      PGADMIN_DEFAULT_PASSWORD: dbt_password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    volumes:
      - dbt_ch4_pgadmin_data:/var/lib/pgadmin
      - ./pg-config.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dbt_ch4_network

volumes:
  dbt_ch4_postgres_data:
    driver: local
  dbt_ch4_pgadmin_data:
    driver: local

networks:
  dbt_ch4_network:
    driver: bridge
