dbt_book_ch5_data_quality_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: dbt_user
      password: dbt_password
      dbname: dbt_demo
      schema: analytics
      threads: 4
      keepalives_idle: 0
      search_path: "analytics,zakka_mall"
      sslmode: disable

    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT', 5432) }}"
      dbname: "{{ env_var('DBT_DATABASE', 'dbt_demo') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'analytics') }}"
      threads: 4
      keepalives_idle: 0
      search_path: "analytics,zakka_mall"
      sslmode: disable

elementary:
  outputs:
    default:
      type: postgres
      host: localhost
      port: 5432
      user: dbt_user
      password: dbt_password
      dbname: dbt_demo
      schema: analytics_elementary
      threads: 4
